name: ${project.name}
description: ${project.description}
version: ${project.version}
main: com.ranull.dualwield.DualWield
author: Ranull

permissions:
  dualwield.attack:
    default: true
    description: Attack entities with off-hand item
  dualwield.mine:
    default: true
    description: Mine blocks with off-hand item