name: Maven Build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          cache: 'maven'
          java-version: |
            8
            16
            17

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: install requests
        run: pip install requests

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: m2-cache
          restore-keys: m2-cache
          save-always: true

      - name: Build necessary remapped spigot libraries into the .m2 cache
        run: python .github/scripts/build_remapped_jars.py

      - name: Build project with Maven
        run: mvn --batch-mode clean verify
